schema: "**/**/*.graphqls"
documents: "**/*.graphql"
plugins:
  - typescript-operations
  - typescript-react-apollo
# ".cache" is now recommended to distinguish from "graphql-let/__generated__"
cacheDir: .cache
